src/Entity/ContactUs.php
<?php

namespace App\Entity;

use App\Repository\ContactUsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ContactUsRepository::class)]
class ContactUs
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $sent_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getSentAt(): ?\DateTimeImmutable
    {
        return $this->sent_at;
    }

    public function setSentAt(\DateTimeImmutable $sent_at): self
    {
        $this->sent_at = $sent_at;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $birthday = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $picture = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Note::class)]
    private Collection $note;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Commande::class)]
    private Collection $commandes;

    public function __construct()
    {
        $this->note = new ArrayCollection();
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    /**
     * @return Collection<int, Note>
     */
    public function getNote(): Collection
    {
        return $this->note;
    }

    public function addNote(Note $note): self
    {
        if (!$this->note->contains($note)) {
            $this->note->add($note);
            $note->setUser($this);
        }

        return $this;
    }

    public function removeNote(Note $note): self
    {
        if ($this->note->removeElement($note)) {
            // set the owning side to null (unless already changed)
            if ($note->getUser() === $this) {
                $note->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setUser($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getUser() === $this) {
                $commande->setUser(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getId();
    }
}

src/Entity/Wine.php
<?php

namespace App\Entity;

use App\Repository\WineRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: WineRepository::class)]
class Wine
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column]
    private ?int $year = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $picture = null;

    #[ORM\Column]
    private ?int $Price = null;

    #[ORM\OneToMany(mappedBy: 'wine', targetEntity: Note::class)]
    private Collection $note;

    #[ORM\ManyToMany(targetEntity: Commande::class, mappedBy: 'wine')]
    private Collection $commandes;

    public function __construct()
    {
        $this->note = new ArrayCollection();
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(int $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->Price;
    }

    public function setPrice(float $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    /**
     * @return Collection<int, Note>
     */
    public function getNote(): Collection
    {
        return $this->note;
    }

    public function addNote(Note $note): self
    {
        if (!$this->note->contains($note)) {
            $this->note->add($note);
            $note->setWine($this);
        }

        return $this;
    }

    public function removeNote(Note $note): self
    {
        if ($this->note->removeElement($note)) {
            // set the owning side to null (unless already changed)
            if ($note->getWine() === $this) {
                $note->setWine(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->addWine($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            $commande->removeWine($this);
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getTitle();
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Commande;
use App\Entity\ContactUs;
use App\Entity\Message;
use App\Entity\Post;
use App\Entity\User;
use App\Entity\Wine;
use App\Form\CompleteUserType;
use App\Form\PictureUserType;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

class UserController extends AbstractController
{
    #[Route('/utilisateur/{id}', name: 'app_user')]
    public function index(ManagerRegistry $doctrine,
                          EntityManagerInterface $entityManager,
                          Request $request,
                          SluggerInterface $slugger): Response
    {
        $user = $this->getUser();

        $totalCommande = $doctrine->getRepository(Commande::class)->getTotalCommandeByUser($user);




        $messages = $doctrine->getRepository(ContactUs::class)->findAll();
        $wines = $doctrine->getRepository(Wine::class)->findAll();
        $commandes =  $doctrine->getRepository(Commande::class)->findBy(['user' => $user]);

        $form= $this->createForm(PictureUserType::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $picture = $form->get('picture')->getData();
            if ($picture) {
                $originalFilename = pathinfo($picture->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $picture->guessExtension();
                try {
                    $picture->move(
                        $this->getParameter('recipe-picture'),
                        $newFilename
                    );
                } catch (FileException $e) {
                }
                $user->setPicture($newFilename);
                $user =  $form->getData();
            }
            $entityManager->persist($user);
            $entityManager->flush();
        }
        return $this->render('user/user.html.twig', [
            'user'          => $user,
            'form'          => $form->createView(),
            'messages'      => $messages,
            'wines'         => $wines,
            'title'         => 'Win\'Export - Gestion comptes',
            'commandes'     =>  $commandes,
            'totalCommande' => $totalCommande,
        ]);
    }

    #[Route('/utilisateur/remove-contact-us/{id}', name: 'delete_form')]
    public function removeContactUs(ManagerRegistry $doctrine,
                           int $id): Response
    {
        $entityManager = $doctrine->getManager();
        $contact = $entityManager->getRepository(ContactUs::class)->findOneBy(['id' => $id]);
        $entityManager->remove($contact);
        $entityManager->flush();

        $this->addFlash('success', 'Message supprimé.');

        
        return $this->redirectToRoute('app_user', ['id' => $id]);
    }
    #[Route('/utilisateur/remove-wine/{id}', name: 'delete_wine')]
    public function removeWine(ManagerRegistry $doctrine,
                           int $id): Response
    {
        $entityManager = $doctrine->getManager();
        $wine = $entityManager->getRepository(Wine::class)->findOneBy(['id' => $id]);
        $entityManager->remove($wine);
        $entityManager->flush();

        $this->addFlash('success', 'Vin supprimé.');


        return $this->redirectToRoute('app_user', ['id' => $id]);
    }

    #[Route('/utilisateur/{user_id}/remove-commande/{commande_id}', name: 'delete_wine_list')]
    public function removeWineList(ManagerRegistry $doctrine,
                                    int $user_id,
                                    int $commande_id): Response
    {

        $user = $doctrine->getRepository(User::class)->find($user_id);
        $commande = $doctrine->getRepository(Commande::class)->find($commande_id);

        $entityManager = $doctrine->getManager();
        $entityManager->remove($commande);
        $entityManager->flush();

        $this->addFlash('success', 'Commande retirée.');


        return $this->redirectToRoute('app_user', ['id' => $user]);
    }
}

templates/user/panier.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ title }}{% endblock %}

{% block body %}
     {% include'fixed/nav_three.html.twig' %}
    <div class="background-image-three"></div>
    <div class="content">
    <div class="user-panier">
        <div class="custom-title-one custom-title-one-form">
            <h3>Votre panier</h3>
            <img src="{{ asset('picture/title/title-bootle-two.png') }}" alt="" class="title-h3">
        </div>
        <div class="panel-user-panier">
            <div class="panier-commandes">
            {% for commande in commandes %}
                    {% if  commande.user.id == app.user.id %}
                            <div class="panier-commandes-unit">
                                <p> {{ commande.number }} x
                                    {% for wines in commande.wine %}
                                    {{ wines.title }}</p>
                                <p class="getTotal">{{ commande.getTotal }}€</p>
                                <button type="button" class="button-custom-three" style="background-color: red;">
                                    <a href="{{ path('delete_wine_list', { 'commande_id' : commande.id, 'user_id' : app.user.id }) }}">
                                        <img src="{{ asset('picture/icones/delete.svg') }}" alt="Lien pour supprimer une commande">
                                    </a>
                                </button>
                                <a href="{{ path('app_wine', { 'id' : wines.id}) }}">
                                    <img src="{{ asset('picture/recipe-picture/' ~ wines.getPicture()) }}" alt="" class="picture-commande">
                                </a>
                            {% endfor %}
                        </div>
                    {% else %}
                    {% endif %}
            {% endfor %}
            </div>
        </div>
    </div>
</div>
{% include'fixed/footer_four.html.twig' %}
{% endblock %}

templates/user/user.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{title}}{% endblock %}
{% block body %}
    {% include'fixed/nav_three.html.twig' %}
    <div class="content">
        <div class="user-gestion">
            <div class="custom-title-one custom-title-one-form">
                <h3>Bonjour, {{ app.user.firstname }}</h3>
                <img src="{{ asset('picture/title/title-user-gestion.png') }}" alt="" class="title-h3">
            </div>
            <div class="responsive-user-coord">
            <ul class="user-coordonnees">
                <li><u>Email</u> : {{ app.user.email }}</li>
                <li><u>Prénom</u> : {{ app.user.firstname }}</li>
                <li><u>Nom</u> : {{ app.user.lastname }}</li>
                <li><u>Anniversaire</u> : {{ app.user.birthday|date("m/d/Y") }}</li>
            </ul>
                {% if app.user.getPicture %}
                <div class="picture-user">
                    <img id="user-picture" src="{{ asset('picture/recipe-picture/' ~ app.user.getPicture()) }}" alt="Photo de profil sans enregistrement.">
                </div>
            {% else %}
                <div class="responsive-form">
                    <h4>Ajouter une photo : </h4>
                    <div class="form-picture-user">
                    {{ form_start(form) }}
                    {{ form_errors(form) }}
                    {{ form_row(form.submit, { 'label': ' '}) }}
                    {{ form_end(form) }}
                </div>
                </div>
            {% endif %}
            </div>
        </div>
        <div class="user-gestion-relative">
            <img src="{{ asset('picture/icones/arrow-bot.svg') }}" alt="">
            <div class="user-button-list">
                <button type="button" class="button-custom-three"><a href="{{ path('app_change_password', { 'id' : app.user.id}) }}">Changer MDP</a></button>
                <button type="button" class="button-custom-three"><a href="{{ path('app_change_picture', { 'id' : app.user.id}) }}">Changer Photo </a></button>
            </div>
            {% if app.user %}
                {% if 'ROLE_ADMIN' in app.user.roles %}
                    <h4>Messages Reçus : </h4>
                    <div class="received-message">
                    {% if messages is not empty %}
                    {% for message in messages %}
                        <div class="card-message">
                            <h5>{{ message.title }}</h5>
                            <p>{{ message.content }}</p>
                            <div class="card-message-buttons">
                                <ul>
                                    <li>{{ message.email }}</li>
                                    <li>{{ message.sentAt|date("m/d/Y") }}</li>
                                </ul>
                                <button type="button" class="button-custom-delete">
                                    <a href="{{ path('delete_form', { 'id' : message.id}) }}">
                                        <img src="{{ asset('picture/icones/delete.svg') }}" alt="Representation bouton supprimer message.">
                                    </a>
                                </button>
                            </div>
                        </div>
                        <div id="horiz-line"></div>
                    {% endfor %}
                    {% else %}
                        <p>Pas de message reçu.</p>
                    {% endif %}
                    </div>
                    <h4 style="margin-top: 5%">Gestion des vins : </h4>
                    <button type="button" class="button-custom-three"><a href="{{ path('app_add_wine') }}">Ajouter Vin + </a></button>
                    <div class="wine-list">
                    {% for wine in wines %}
                        <div class="wine-list-unit">
                                <h5>{{ wine.title }}</h5>
                            <div class="wine-unit-desc">
                                <ul>
                                    <li>Prix : {{ wine.price }}</li>
                                    <li>Année : {{ wine.year }}</li>
                                </ul>
                                <div class="button-list">
                                    <button type="button" class="button-custom-three"><a href="{{ path('app_update_wine', { 'id' : wine.id}) }}">Modifier</a></button>
                                    <button type="button" class="button-custom-three"><a href="{{ path('delete_wine', { 'id' : wine.id}) }}">Supprimer</a></button>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    </div>
                {% elseif  'ROLE_USER' in app.user.roles %}
                    <h4>Votre panier : </h4>
                    <div class="list-com">
                    {% for commande in commandes %}
                        {% if  commande.user.id == app.user.id %}
                            <div class="list-commades">
                                <p> {{ commande.number }} x
                                {% for wines in commande.wine %}
                                    {{ wines.title }}</p> <p class="getTotal">{{ commande.getTotal }}€</p>
                                <a href="{{ path('app_wine', { 'id' : wines.id}) }}">
                                    <img src="{{ asset('picture/recipe-picture/' ~ wines.getPicture()) }}" alt="">
                                </a>
                                {% endfor %}
                                <button type="button" class="button-custom-three" style="background-color: red;">
                                    <a href="{{ path('delete_wine_list', { 'commande_id' : commande.id, 'user_id' : app.user.id }) }}">
                                        <img src="{{ asset('picture/icones/cross.png') }}" alt="Lien pour supprimer une commande">
                                    </a>
                                </button>
                            </div>
                        {% else %}
                        {% endif %}
                    {% endfor %}
                    </div>
                    <div class="total-valid">
                        <p> Total :
                            {% if totalCommande == 0 %}
                                <p>Vide</p>
                            {% else %}
                            {{ totalCommande }}€
                            {% endif %}
                        </p>
                        <button class="button-valid">
                            <a href="">
                                Valider
                            </a>
                        </button>
                    </div>

                {% endif %}
            {% else %}
            {% endif %}
        </div>
        {% include'fixed/footer_two.html.twig' %}
        <div id="success-message-async"></div>
        {% for message in app.flashes('success') %}
            <div class="success-custom">
                {{ message }}
            </div>
        {% endfor %}
        <script>
            setTimeout(function() {
                const successCustom = document.querySelector('.success-custom');
                if (successCustom !== null) {
                    successCustom.classList.add('fadeout');
                }
            }, 1500);
        </script>
        <script>
            const elements = document.querySelectorAll('.getTotal');

            // Initialiser une variable pour stocker la somme totale
            let total = 0;

            // Boucler sur chaque élément et ajouter sa valeur au total
            elements.forEach(element => {
                total += parseFloat(element.textContent);
            });

        </script>
    </div>
{% endblock %}